language: python
python:
  - 2.7
install:
  - mkdir -p buildout-cache/{eggs,downloads}
  - ./bootstrap.sh -c travis.cfg
script:
  - bin/code-analysis
  - bin/test
  - bin/createcoverage
after_success:
  - pip install coveralls
  - coveralls

notifications:
  email:
    - alecpm@gmail.com
